# Staging environment configuration
# Inherits from deploy.yml and overrides specific values

servers:
  web:
    - staging-server.your-domain.com

env:
  clear:
    RACK_ENV: staging
    SALSIFY_FILE_PATH: /app/data/staging_file.txt

proxy:
  host: staging.your-domain.com

# Use smaller resource limits for staging
service:
  memory: 512m
  cpus: 0.5